### ISSUE TITLE
Create sequence diagram for bookmarking

### ISSUE THREAD

**Issue by zbuseaydin** [bounswe/bounswe2024group4#112] opened 2024-04-25 18:25 UTC
### Issue Type

Deliverable

### Issue Description

Create and add the relevant diagrams in the [sequence diagrams page](https://github.com/bounswe/bounswe2024group4/wiki/Sequence-Diagrams).

**Comment by fatih260** [comment] 2024-04-29 11:58
This issue is a duplicate of this closed [issue](https://github.com/bounswe/bounswe2024group4/issues/115)

**Closed by fatih260** 2024-04-29 11:58 UTC
Labels: priority: medium, deliverable
